# Optimizable weights contains the list of weights we want to optimize, their bounds and their
# reconfigure name. This file is unused and serves as a template with all posible tuning parameters.
weights_names:
  - ['Q1', 'Q2', 'R1', 'R2', 'R3', 'q', 'lag_compensation_time', 'Df', 'Dr', 'Cf', 'Cr', 'Bf', 'Br']

lower_bounds:
  - [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.2, 0.2, 1.0, 1.0, 3.0, 3.0]

upper_bounds:
  - [1000, 1000, 1000, 1000, 1000, 1000, 1, 3.0, 3.0, 2.0, 2.0, 10.0, 10.0]

initial_values:
  - [100.0, 200.0, 0.2, 0.3, 0.2, 3.5, 0.03, 0.65, 1.0, 1.5, 1.45, 5.2, 8.5]

reconfigure_names:
    - '/car_1/controller_node'
